#!/usr/bin/env sh
export SXHKD_SHELL=/usr/bin/sh
if [ -e ./.profile ]; then . ./.profile; fi

# Keyboard repeat
xset r rate 200 40
# Screensaver
xset s on
xset s 180

# Utilities
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x nm-applet > /dev/null || nm-applet &
pgrep -x xss-lock > /dev/null || xss-lock xsecurelock &

# BSPWM
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
