#!/usr/bin/env bash

case $1 in
    build | b )         nix-shell -p nixFlakes --run "nix build --experimental-features 'nix-command flakes'"
                        ;;
    update | u )        nix-shell -p nixFlakes --run "nix flake update --recreate-lock-file --experimental-features 'nix-command flakes'"
                        ;;
    install | i)        nix-shell -p nixFlakes --run "nix build --experimental-features 'nix-command flakes' && ./result/activate"
                        ;;
    * )                 echo "Unrecognized command $1"
                        ;;
esac
